############################################################
# +------------------------------------------------------+ #
# |                       qSpleef                        | #
# |   Source:   https://github.com/QarthO/qSpleef        | #
# |   Wiki:     https://wiki.quartzdev.gg/qspleef        | #
# |   Download: https://modrinth.com/plugin/qgptrust/    | #
# |   Discord:  https://quartzdev.gg/discord/            | #
# |   Donate:   https://paypal.me/qartho                 | #
# +------------------------------------------------------+ #
############################################################

# Don't change these unless you know what you're doing
config-version: "1.0-alpha1"
debug: false

# Checks for update upon server start, or when an admin joins
check-for-updates: true

# If enabled, everyone has access to basic spleef permissions
# even without permissions
# Same as giving 'qspleef.basic' permission to your default group
default-access: true

############################################################
# +------------------------------------------------------+ #
# |                      Game Start                      | #
# +------------------------------------------------------+ #
############################################################

game-start:
#
  countdown:
#    What times should
      times:
        - 30
        - 10
        - 5
        - 4
        - 3
        - 2
        - 1
      chat:
        enabled: false
      title:
        enabled: true
  #      Available titles positions: actionbar, subtitle, title
        position: title
      sound:
        enabled: true
        #          List of Available sounds: https://jd.papermc.io/paper/1.12/org/bukkit/Sound.html
        name: "BLOCK_DISPENSER_FAIL"
        #          Value between 0.0 and 1.0, The higher the value, the louder the sound.
        volume: 1.0
        #          Value between 0.0 and 2.0. The higher the value, the higher the pitch.
        pitch: 1.0
  #  When the game starts should players be teleported randomly around the arena
  randomize-player-positions:
    enabled: true
    #    At what time should the players be teleported
    countdown-time: 5
    #    Should they be frozen after being teleported until the game officially starts
    freeze: true

############################################################
# +------------------------------------------------------+ #
# |                      Broadcasts                      | #
# +------------------------------------------------------+ #
############################################################

broadcast:
  #  Broadcasted when a player win a gamea
  #  Edited in 'messages.yml' in 'broadcast-win'
  win:
    enabled: true
    everyone: true
  #  Broadcasted when a player joins a game
  #  Edited in 'messages.yml' in 'broadcast-join'
  join:
    enabled: true
    everyone: false
  #  Broadcasted when a player leaves a game
  #  Edited in 'messages.yml' in 'broadcast-leave'
  leave:
    enabled: true
    everyone: false
  #  Broadcasted when the countdown starts, (only 1 time)
  #  Edited in 'messages.yml' in 'broadcast-first-countdown'
  first-countdown:
    enabled: true
    everyone: true
  #  Broadcasted at the start of a game
  #  Edited in 'messages.yml' in 'broadcast-start'
  start:
    enabled: true
    everyone: false

############################################################
# +------------------------------------------------------+ #
# |                 Sign Text Formatting                 | #
# +------------------------------------------------------+ #
############################################################

# Signs support MiniMessage color formatting
# For more info: https://docs.advntr.dev/minimessage/format.html
# Available Spleef Placeholders:
# <prefix>  | Required: Yes | The prefix can be edited in the 'messages.yml'
# <arena>   | Required: Yes | Name of the arena
# <status>  | Required: No  | The state of the arena, can be edited below
# <info>    | Required: No  | Custom message depending on the arena state

# Arena States:
# default     | Not a state, but text defaults to this if none given
# locked      | When an arena is locked by an admin using '/spleef lock <arena>'
# ready       | When an arena is ready to be joined
# starting    | When an arena has started it's countdown to begin playing
# playing     | When a game is currently active
# resetting   | After a game is finished, and the floor is being reset

# Note: To set up a sign, you must use the '/spleef set sign' commmand
sign:
  text:
    line-1: "<chat-prefix>"
    line-2: "<gold><bold><arena>"
    line-3: "<info>"
    line-4: "<status>"
  placeholders:
    info:
      default: ""
      ready: "<green>Click to join"
      playing: "<green>Click to spectate"
    status:
      default: ""
      locked: "<red>LOCKED"
      ready: "<green><current-players>/<max-players>"
      playing: "<aqua><current-players>/<max-players>"
      resetting: "<yellow>Resetting"

#  Displays a message on the actionbar when hovering over a spleef sign
  hover:
    enabled: true
#    Message can change depending on
#    Leave "" empty for no message to be displayed
    message:
      default: ""
      locked: "<red><arena> is locked"
      ready: "<green>Right click to join"
      playing: "<green>Right click to spectate"
      resetting: "<yellow>Resetting... Please wait"


############################################################
# +------------------------------------------------------+ #
# |                Spleef Arena Defaults                 | #
# +------------------------------------------------------+ #
############################################################


# These are the default settings for an arena
# Arenas with defaults enabled will use these instead
default-arena-settings:
#  Min players required to start the arena
  min-players: 6
#  Maximum amount of players allowed in an arena
  max-players: 24

  rewards:
#    Amount of money to give the player
#    Requires an economy plugin such as fault
    money: 0

#    Server command to be ran after a game is complete
#    Supported Placeholders:
#     <player>  | The player that won the arena
#     <arena>   | Name of the arena
    commands:
#      - crate give <player> spleef<arena> 1
#      - give <player> minecraft:diamond 1
  gamerules:

#    If players recieve snowballs after destroying a block
    snowballs:
      enabled: true
#      How many snowballs per block destroyed
      amount-per-block: 8
#      How mnay snowballs each player starts with when the game starts
      start: 0

#    If a player stands still destroy the block underneath them
    anti-camping:
      enabled: true
#      How long (seconds) until the block is broken if the player is in the same spot
      time: 5
#      A warning system so a player knows they should move or not when standing still
      warning:
        enabled: true
        sound:
          enabled: true
#          List of Available sounds: https://jd.papermc.io/paper/1.12/org/bukkit/Sound.html
          name: "BLOCK_DISPENSER_FAIL"
#          Value between 0.0 and 1.0, The higher the value, the louder the sound.
          volume: 1.0
#          Value between 0.0 and 2.0. The higher the value, the higher the pitch.
          pitch: 2.0
        title:
          enabled: true
#          Available Titles: actionbar, subtitle, title
          position: 'actionbar'
        countdown:
          - 3
          - 2
          - 1