############################################################
# +------------------------------------------------------+ #
# |                    qSpleef Config                    | #
# |   Source:   https://github.com/QarthO/qSpleef        | #
# |   Wiki:     https://wiki.quartzdev.gg/qspleef        | #
# |   Download: https://modrinth.com/plugin/qgptrust/    | #
# |   Discord:  https://quartzdev.gg/discord/            | #
# |   Donate:   https://paypal.me/qartho                 | #
# +------------------------------------------------------+ #
############################################################

# Don't change these unless you know what you're doing
config-version: "1.0-alpha1"
debug: false

############################################################
# +------------------------------------------------------+ #
# |                    General Settings                  | #
# +------------------------------------------------------+ #
############################################################

# Checks for update upon server start, or when an admin joins
check-for-updates: true

# If enabled, everyone has access to basic spleef permissions
# even without permissions
# Same as giving 'qspleef.basic' permission to your default group
default-access: true

# Should spectators be able to join the arena
spectators:
  enabled: true

storage:
#    Supported types: yml, sqlite, mysql
  type: "yml"
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
    database: "qspleef"
    max_connections: 8

############################################################
# +------------------------------------------------------+ #
# |                      Game Start                      | #
# +------------------------------------------------------+ #
############################################################

game-start:
#
  countdown:
#    What times should
      times:
        - 30
        - 10
        - 5
        - 4
        - 3
        - 2
        - 1
      chat:
        enabled: false
      title:
        enabled: true
  #      Available titles positions: actionbar, subtitle, title
        position: title
      sound:
        enabled: true
#          List of Available sounds: https://jd.papermc.io/paper/1.12/org/bukkit/Sound.html
        name: "BLOCK_DISPENSER_FAIL"
#          Value between 0.0 and 1.0, The higher the value, the louder the sound.
        volume: 1.0
#          Value between 0.0 and 2.0. The higher the value, the higher the pitch.
        pitch: 1.0
#  When the game starts should players be teleported randomly around the arena
  randomize-player-positions:
    enabled: true
#    At what time should the players be teleported
    countdown-time: 5
#    Should they be frozen after being teleported until the game officially starts
    freeze: true

############################################################
# +------------------------------------------------------+ #
# |                      Broadcasts                      | #
# +------------------------------------------------------+ #
############################################################

broadcast:
#  Broadcasted when a player win a gamea
#  Edited in 'messages.yml' in 'broadcast-win'
  win:
    enabled: true
    everyone: true
#  Broadcasted when a player joins a game
#  Edited in 'messages.yml' in 'broadcast-join'
  join:
    enabled: true
    everyone: false
#  Broadcasted when a player leaves a game
#  Edited in 'messages.yml' in 'broadcast-leave'
  leave:
    enabled: true
    everyone: false
#  Broadcasted when the countdown starts, (only 1 time)
#  Edited in 'messages.yml' in 'broadcast-first-countdown'
  first-countdown:
    enabled: true
    everyone: true
#  Broadcasted at the start of a game
#  Edited in 'messages.yml' in 'broadcast-start'
  start:
    enabled: true
    everyone: false

############################################################
# +------------------------------------------------------+ #
# |                        Signs                         | #
# +------------------------------------------------------+ #
############################################################

# Note: To set up a sign, you must use the '/spleef set sign' commmand
# In order to use a sign, players need 'spleef.basic' permission
# In order to create a sign, players need 'spleef.admin' permission
sign:
#  Displays a message on the actionbar when hovering over a spleef sign
  hover:
    enabled: true

############################################################
# +------------------------------------------------------+ #
# |                    Player Stats                      | #
# +------------------------------------------------------+ #
############################################################

stats:
  enabled: true
  webui:
    enabled: false
    port: 8840
    internal-ip: 0.0.0.0
    external-ip: "https://yourdomain.com/spleef"


############################################################
# +------------------------------------------------------+ #
# |                 Simple Voice Chat                    | #
# +------------------------------------------------------+ #
############################################################

# Download:  https://modrinth.com/plugin/simple-voice-chat

# If Simple Voice Chat is installed on the server, qspleef can
# create group calls for games

# Default settings are recommend
# Spectators being in a group, but players not means spectators can
# hear the players, but players can't hear them

# This feature can be turned off, and simple voice chat will work
# normally. This is strictly for syncing groups.

voice-groups:
  enabled: true
#  Should players be automatically put into a group
  players:
    enabled: false
#      Name of the group
#      <arena> is the name of the arena
    group-name: "qSpleef-Players: -<arena>"
#      Password for the group, leave blank for no password
#       *Note: If password is empty, anyone might be able to join
#      <arena> is the name of the arena
#      <rng> is a 4 digit random number
#      Example: "<arena>-<rng>" turns to "spleef1-3526"
    password: "<arena>-<rng>"
#  Should spectators be put into a seperate group
#  If disabled, spectators will stay in the players group
  spectators:
    enabled: true
    group-name: "qSpleef-Spectators: <arena>"
    password: "<arena>-<rng>"

############################################################
# +------------------------------------------------------+ #
# |                Spleef Arena Defaults                 | #
# +------------------------------------------------------+ #
############################################################


# These are the default settings for an arena
# Arenas with defaults enabled will use these instead
default-arena-settings:
#  Min players required to start the arena
  min-players: 6
#  Maximum amount of players allowed in an arena
  max-players: 24

  rewards:
#    Amount of money to give the player
#    Requires an economy plugin such as fault
    money: 0

#    Server command to be ran after a game is complete
#    Supported Placeholders:
#     <player>  | The player that won the arena
#     <arena>   | Name of the arena
    commands:
#      - crate give <player> spleef<arena> 1
#      - give <player> minecraft:diamond 1
  gamerules:

#    If players recieve snowballs after destroying a block
    snowballs:
      enabled: true
#      How many snowballs per block destroyed
      amount-per-block: 8
#      How mnay snowballs each player starts with when the game starts
      start: 0

#    If a player stands still destroy the block underneath them
    anti-camping:
      enabled: true
#      How long (seconds) until the block is broken if the player is in the same spot
      time: 5
#      A warning system so a player knows they should move or not when standing still
      warning:
        enabled: true
        sound:
          enabled: true
#          List of Available sounds: https://jd.papermc.io/paper/1.12/org/bukkit/Sound.html
          name: "BLOCK_DISPENSER_FAIL"
#          Value between 0.0 and 1.0, The higher the value, the louder the sound.
          volume: 1.0
#          Value between 0.0 and 2.0. The higher the value, the higher the pitch.
          pitch: 2.0
        title:
          enabled: true
#          Available Titles: actionbar, subtitle, title
          position: "actionbar"
        countdown:
          - 3
          - 2
          - 1